python3 generate_jobs.py device_load=cpu num_processes=10 arrival_time=flow
python3 generate_jobs.py device_load=cpu num_processes=10 arrival_time=batch
python3 generate_jobs.py device_load=cpu num_processes=10 arrival_time=hybrid
python3 generate_jobs.py device_load=cpu num_processes=25 arrival_time=flow
python3 generate_jobs.py device_load=cpu num_processes=25 arrival_time=batch
python3 generate_jobs.py device_load=cpu num_processes=25 arrival_time=hybrid
python3 generate_jobs.py device_load=cpu num_processes=50 arrival_time=flow
python3 generate_jobs.py device_load=cpu num_processes=50 arrival_time=batch
python3 generate_jobs.py device_load=cpu num_processes=50 arrival_time=hybrid
python3 generate_jobs.py device_load=io num_processes=10 arrival_time=flow
python3 generate_jobs.py device_load=io num_processes=10 arrival_time=batch
python3 generate_jobs.py device_load=io num_processes=10 arrival_time=hybrid
python3 generate_jobs.py device_load=io num_processes=25 arrival_time=flow
python3 generate_jobs.py device_load=io num_processes=25 arrival_time=batch
python3 generate_jobs.py device_load=io num_processes=25 arrival_time=hybrid
python3 generate_jobs.py device_load=io num_processes=50 arrival_time=flow
python3 generate_jobs.py device_load=io num_processes=50 arrival_time=batch
python3 generate_jobs.py device_load=io num_processes=50 arrival_time=hybrid
python3 generate_jobs.py device_load=net num_processes=10 arrival_time=flow
python3 generate_jobs.py device_load=net num_processes=10 arrival_time=batch
python3 generate_jobs.py device_load=net num_processes=10 arrival_time=hybrid
python3 generate_jobs.py device_load=net num_processes=25 arrival_time=flow
python3 generate_jobs.py device_load=net num_processes=25 arrival_time=batch
python3 generate_jobs.py device_load=net num_processes=25 arrival_time=hybrid
python3 generate_jobs.py device_load=net num_processes=50 arrival_time=flow
python3 generate_jobs.py device_load=net num_processes=50 arrival_time=batch
python3 generate_jobs.py device_load=net num_processes=50 arrival_time=hybrid
python3 generate_jobs.py device_load=dl num_processes=10 arrival_time=flow
python3 generate_jobs.py device_load=dl num_processes=10 arrival_time=batch
python3 generate_jobs.py device_load=dl num_processes=10 arrival_time=hybrid
python3 generate_jobs.py device_load=dl num_processes=25 arrival_time=flow
python3 generate_jobs.py device_load=dl num_processes=25 arrival_time=batch
python3 generate_jobs.py device_load=dl num_processes=25 arrival_time=hybrid
python3 generate_jobs.py device_load=dl num_processes=50 arrival_time=flow
python3 generate_jobs.py device_load=dl num_processes=50 arrival_time=batch
python3 generate_jobs.py device_load=dl num_processes=50 arrival_time=hybrid
python3 generate_jobs.py device_load=balanced num_processes=10 arrival_time=flow
python3 generate_jobs.py device_load=balanced num_processes=10 arrival_time=batch
python3 generate_jobs.py device_load=balanced num_processes=10 arrival_time=hybrid
python3 generate_jobs.py device_load=balanced num_processes=25 arrival_time=flow
python3 generate_jobs.py device_load=balanced num_processes=25 arrival_time=batch
python3 generate_jobs.py device_load=balanced num_processes=25 arrival_time=hybrid
python3 generate_jobs.py device_load=balanced num_processes=50 arrival_time=flow
python3 generate_jobs.py device_load=balanced num_processes=50 arrival_time=batch
python3 generate_jobs.py device_load=balanced num_processes=50 arrival_time=hybrid