python3 generate_jobs.py num_processes=10 arrival_time=flow device_load=cpu 
python3 generate_jobs.py num_processes=10 arrival_time=batch device_load=cpu 
python3 generate_jobs.py num_processes=10 arrival_time=hybrid device_load=cpu 
python3 generate_jobs.py num_processes=25 arrival_time=flow device_load=cpu 
python3 generate_jobs.py num_processes=25 arrival_time=batch device_load=cpu 
python3 generate_jobs.py num_processes=25 arrival_time=hybrid device_load=cpu 
python3 generate_jobs.py num_processes=50 arrival_time=flow device_load=cpu 
python3 generate_jobs.py num_processes=50 arrival_time=batch device_load=cpu 
python3 generate_jobs.py num_processes=50 arrival_time=hybrid device_load=cpu 
python3 generate_jobs.py num_processes=10 arrival_time=flow device_load=io
python3 generate_jobs.py num_processes=10 arrival_time=batch device_load=io
python3 generate_jobs.py num_processes=10 arrival_time=hybrid device_load=io
python3 generate_jobs.py num_processes=25 arrival_time=flow device_load=io
python3 generate_jobs.py num_processes=25 arrival_time=batch device_load=io
python3 generate_jobs.py num_processes=25 arrival_time=hybrid device_load=io
python3 generate_jobs.py num_processes=50 arrival_time=flow device_load=io
python3 generate_jobs.py num_processes=50 arrival_time=batch device_load=io
python3 generate_jobs.py num_processes=50 arrival_time=hybrid device_load=io
python3 generate_jobs.py num_processes=10 arrival_time=flow device_load=net
python3 generate_jobs.py num_processes=10 arrival_time=batch device_load=net
python3 generate_jobs.py num_processes=10 arrival_time=hybrid device_load=net
python3 generate_jobs.py num_processes=25 arrival_time=flow device_load=net
python3 generate_jobs.py num_processes=25 arrival_time=batch device_load=net
python3 generate_jobs.py num_processes=25 arrival_time=hybrid device_load=net
python3 generate_jobs.py num_processes=50 arrival_time=flow device_load=net
python3 generate_jobs.py num_processes=50 arrival_time=batch device_load=net
python3 generate_jobs.py num_processes=50 arrival_time=hybrid device_load=net
python3 generate_jobs.py num_processes=10 arrival_time=flow device_load=dl
python3 generate_jobs.py num_processes=10 arrival_time=batch device_load=dl
python3 generate_jobs.py num_processes=10 arrival_time=hybrid device_load=dl
python3 generate_jobs.py num_processes=25 arrival_time=flow device_load=dl
python3 generate_jobs.py num_processes=25 arrival_time=batch device_load=dl
python3 generate_jobs.py num_processes=25 arrival_time=hybrid device_load=dl
python3 generate_jobs.py num_processes=50 arrival_time=flow device_load=dl
python3 generate_jobs.py num_processes=50 arrival_time=batch device_load=dl
python3 generate_jobs.py num_processes=50 arrival_time=hybrid device_load=dl
python3 generate_jobs.py num_processes=10 arrival_time=flow device_load=balanced
python3 generate_jobs.py num_processes=10 arrival_time=batch device_load=balanced
python3 generate_jobs.py num_processes=10 arrival_time=hybrid device_load=balanced
python3 generate_jobs.py num_processes=25 arrival_time=flow device_load=balanced
python3 generate_jobs.py num_processes=25 arrival_time=batch device_load=balanced
python3 generate_jobs.py num_processes=25 arrival_time=hybrid device_load=balanced
python3 generate_jobs.py num_processes=50 arrival_time=flow device_load=balanced
python3 generate_jobs.py num_processes=50 arrival_time=batch device_load=balanced
python3 generate_jobs.py num_processes=50 arrival_time=hybrid device_load=balanced